// <auto-generated />
namespace AutomationShell48.UI.Properties
{
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get { return defaultInstance; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Light")]
        public string LastTheme
        {
            get { return ((string)this["LastTheme"]); }
            set { this["LastTheme"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string IsSidebarCollapsed
        {
            get { return ((string)this["IsSidebarCollapsed"]); }
            set { this["IsSidebarCollapsed"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("main")]
        public string LastSelectedNavKey
        {
            get { return ((string)this["LastSelectedNavKey"]); }
            set { this["LastSelectedNavKey"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1280")]
        public string WindowWidth
        {
            get { return ((string)this["WindowWidth"]); }
            set { this["WindowWidth"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800")]
        public string WindowHeight
        {
            get { return ((string)this["WindowHeight"]); }
            set { this["WindowHeight"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public string WindowTop
        {
            get { return ((string)this["WindowTop"]); }
            set { this["WindowTop"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public string WindowLeft
        {
            get { return ((string)this["WindowLeft"]); }
            set { this["WindowLeft"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string HasSavedWindowBounds
        {
            get { return ((string)this["HasSavedWindowBounds"]); }
            set { this["HasSavedWindowBounds"] = value; }
        }
    }
}
